pbf.settings:
  type: config_object
  label: 'Pbf settings'
  mapping:
    pbf_roles_gids:
      type: sequence
      label: 'Role - Grant Id mapping array'
      sequence:
        type: integer
        label: 'Grant ID'

# Schema for the configuration of the Pbf field type.
field.storage_settings.pbf:
  type: mapping
  label: 'Pbf field storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

field.field_settings.pbf:
  type: mapping
  label: 'Pbf field settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Entity reference selection plugin settings'
    priority:
      type: integer
      label: 'Priority access'
    user_method:
      type: string
      label: 'Method to grant access for user referenced'
    synchronized_with:
      type: string
      label: 'Field synchronize an another field'
    synchronized_by:
      type: string
      label: 'Field is synchronized by an another field'
    synchronized_from_target:
      type: integer
      label: 'Targeted field can synchronize source field'

field.value.pbf:
  type: mapping
  label: 'Default value'
  mapping:
    target_id:
      type: string
      label: 'Value'
    target_uuid:
      type: string
      label: 'Target UUID'
    grant_public:
      type: integer
      label: 'Public access'
    grant_view:
      type: integer
      label: 'Grant view'
    grant_update:
      type: integer
      label: 'Grant update'
    grant_delete:
      type: integer
      label: 'Grant delete'

field.widget.settings.pbf_widget:
 type: mapping
 label: 'PBF widget settings'
 mapping:
   match_operator:
     type: string
     label: 'Method for autocomplete suggestion'
   size:
     type: string
     label: 'Size for textfield'
   placeholder:
     type: string
     label: 'Placeholder for textfield'
   grant_global:
     type: integer
     label: 'Set grant settings generally'
   grant_public:
     type: integer
     label: 'Public access'
   grant_view:
     type: integer
     label: 'Grant view'
   grant_update:
     type: integer
     label: 'Grant update'
   grant_delete:
     type: integer
     label: 'Grant delete'

field.formatter.settings.pbf_formatter_default:
  type: mapping
  label: 'Pbf display format settings'
  mapping:
    link:
      type: boolean
      label: 'Link label to the referenced entity'