<?php

/**
 * @file
 * Module file.
 */

use Drupal\entity_reference_integrity\EntityReferenceIntegrityEntityHandler;

/**
 * Implements hook_entity_type_alter().
 */
function entity_reference_integrity_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface $entity_type */
  foreach ($entity_types as $entity_type) {
    if (!$entity_type->hasHandlerClass('entity_reference_integrity')) {
      $entity_type->setHandlerClass('entity_reference_integrity', EntityReferenceIntegrityEntityHandler::class);
    }
  }
}
