# Schema for the domain access plugins.

views.access.domain_access_admin:
  type: mapping
  label: 'Domain Access: Administer domain editors'
views.access.domain_access_editor:
  type: mapping
  label: 'Domain Access: Edit domain content'
views.argument.domain_access_argument:
  type: views_argument
  label: 'Domain Access'
views.field.domain_access_field:
  type: views_field
  label: 'Domain Access'
  mapping:
    click_sort_column:
      type: string
      label: 'Column used for click sorting'
    type:
      type: string
      label: 'Formatter'
    settings:
      label: 'Settings'
      type: field.formatter.settings.[%parent.type]
    group_column:
      type: string
      label: 'Group by column'
    group_columns:
      type: sequence
      label: 'Group by columns'
      sequence:
        type: string
        label: 'Column'
    group_rows:
      type: boolean
      label: 'Display all values in the same row'
    delta_limit:
      type: integer
      label: 'Field'
    delta_offset:
      type: integer
      label: 'Offset'
    delta_reversed:
      type: boolean
      label: 'Reversed'
    delta_first_last:
      type: boolean
      label: 'First and last only'
    multi_type:
      type: string
      label: 'Display type'
    separator:
      type: label
      label: 'Separator'
    field_api_classes:
      type: boolean
      label: 'Use field template'
views.filter.domain_access_current_all_filter:
  type: views_filter
  label: 'Current Domain or All Domains'
views.filter.domain_access_filter:
  type: views.filter.in_operator
  label: 'Domain Access'
