<?php

/**
 * @file
 * Drupal translation template extractor.
 *
 * This module helps people extract translatable strings from Drupal source
 * code. The user interface allows translators to choose which part of the
 * current Drupal instance to translate. The module also provides an API for
 * other modules (such as coder and l10n_server) to use.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function potx_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'potx.extract_translation':
      return '<p>' . t('This page allows you to generate translation templates for module and theme files. Select the module or theme you wish to generate a template file for. A single Gettext Portable Object (Template) file is generated, so you can easily save it and start translation.') . '</p>';
  }
}
