<?php

/**
 * @file
 * Open external links in new tab.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_link_alter().
 *
 * Add target="_blank" to all external links.
 */
function external_links_new_tab_link_alter(&$variables) {
  if ($variables['url']->isExternal()) {
    $variables['options']['attributes']['target'] = '_blank';
    $variables['options']['attributes']['rel'] = 'noopener';
  }
}

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function external_links_new_tab_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the external_links_new_tab module.
    case 'help.page.external_links_new_tab':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Automatically open (menu) links in a new tab') . '</p>';
      return $output;

    default:
  }
}
