<?php

/**
 * @file
 * Contains install and update functions for XLS Views Data Export.
 */

/**
 * Implements hook_requirements().
 */
function xls_views_data_export_requirements($phase) {
  $requirements = [];
  if ($phase == 'install') {
    if (!extension_loaded('zip')) {
      $requirements['commerce'] = [
        'description' => t('Commerce requires the zip PHP extension.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}