<?php

/**
 * @file
 * Contains xls_views_data_export.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_views_plugins_style_alter().
 *
 * Overrides old XLS Plugin to do provide a form where the
 * old file can be inputted such that it will be appended
 * to a file on the fly.
 *
 * Unfortunately there isn't any non-atomic way of doing
 * this that I know of without also creating a new Display
 * Plugin.
 */
function xls_views_data_export_views_plugins_display_alter(&$definitions){
  // add new options to the schema
  if(isset($definitions['data_export'])){
    $definitions['data_export']['class'] = 'Drupal\xls_views_data_export\Plugin\views\display\XlsDataExport';
  }
}

/**
 * Implements hook_config_schema_info_alter.
 *
 * Adds default fid and worksheet name settings to 
 * data export schema.
 */
function hook_config_schema_info_alter(&$definitions){
  $definitions['views.display.data_export']['mapping']['default_fid'] = array(
    'type' => 'string',
    'label' => 'Default File'
  );
  $definitions['views.display.data_export']['mapping']['default_worksheet_name'] = array(
    'type' => 'string',
    'label' => 'Default Worksheet Name'
  );
  $definitions['views.display.data_export']['mapping']['default_override_sheet'] = array(
    'type' => 'string',
    'label' => 'Override Existing Worksheet By Default'
  );
  $definitions['views.display.data_export']['mapping']['flip_path'] = array(
    'type' => 'boolean',
    'label' => 'Switch Export Path to Regular View Path'
  );
}