export const LOAD_ACTIVITIES_SUCCESS = 'LOAD_ACTIVITIES_SUCCESS';
export const LOAD_ACTIVITY_SUCCESS = 'LOAD_ACTIVITY_SUCCESS';  
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'; 
export const LOAD_PROJECT_SUCCESS = 'LOAD_PROJECT_SUCCESS';  
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'; 
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';  
