<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\entity_reference_integrity_enforce\FormAlter;
use Drupal\entity_reference_integrity_enforce\EntityPredelete;

/**
 * Implements hook_form_alter().
 */
function entity_reference_integrity_enforce_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(FormAlter::class)
    ->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_entity_predelete().
 */
function entity_reference_integrity_enforce_entity_predelete(EntityInterface $entity) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityPredelete::class)
    ->entityDelete($entity);
}

/**
 * Implements hook_module_implements_alter().
 */
function entity_reference_integrity_enforce_module_implements_alter(&$implementations, $hook) {
  if ($hook !== 'entity_predelete') {
    return;
  }
  unset($implementations['entity_reference_integrity_enforce']);
  $implementations = ['entity_reference_integrity_enforce' => FALSE] + $implementations;
}
