name: Domain Site Settings
type: module
description: 'Basic Site Setting for Domains.'
dependencies:
  - domain
  - domain_config

package: Domain
# core: 8.x
configure: domain_site_settings.list

# Information added by Drupal.org packaging script on 2017-04-04
version: '8.x-1.2'
core: '8.x'
project: 'domain_site_settings'
datestamp: 1491339784
